### ISSUE TITLE
Streamdiffusion compatibility?

### ISSUE THREAD

**Issue by ccarmatic** [madebyollin/taesdv#1]
In Streamdiffusion, TAESD is used like this:

 **`stream.vae = AutoencoderTiny.from_pretrained("madebyollin/taesd").to(device=pipe.device, dtype=pipe.dtype)`**

then, the actual usage

```
x_output = stream(input_image)

output_image = postprocess_image(x_output, output_type="pil")[0]
output_image= np.array(output_image)
#the rest of the code
```

But TAESDV is different from TAESD and cannot work like this

for instance, Streamdiffusion's pipeline.py contains this:
```
    def decode_image(self, x_0_pred_out: torch.Tensor) -> torch.Tensor:
        output_latent = self.vae.decode(
            x_0_pred_out / self.vae.config.scaling_factor, return_dict=False
        )[0]
        return output_latent
```
but taesdv.py contains this
```
    def decode_frame(self, x, mem=None):

        assert x.ndim == 4 and x.shape[1] == 4, f"Could not decode frame of shape {x.shape}"
        out_mem, in_mem = [], None if mem is None else list(mem)
        for b in self.decoder:
            if isinstance(b, MemBlock):
                out_mem.append(x)
                x = b(x, x * 0 if in_mem is None else in_mem.pop(0))
            else:
                x = b(x)
        return DecoderResult(x, out_mem)
```
Streamdiffusion calls the `decode` method but TAESDV has `decode_frame` , and there is also the added 'mem' argument 
I am investigating how to make TAESDV work with Streamdiffusion, can anyone help?

**Comment by madebyollin** [comment]
I think you can probably solve this by wrapping `TAESDV` to make it behave more like an `AutoencoderTiny`

```python
import torch.nn as nn
from taesdv import TAESDV
import torch

class DotDict(dict):
    def __getattr__(self, name):
        if name in self:
            return self[name]
        raise AttributeError()
    __setattr__ = dict.__setitem__

class DiffusersStyleStatefulTAESDVWrapper(nn.Module):
    def __init__(self):
        super().__init__()
        self.dtype = torch.float16
        self.taesdv = TAESDV().to(self.dtype).eval().requires_grad_(False)
        self.mem = None
        self.config = DotDict(scaling_factor=1.0)
    def encode(self, x):
        return DotDict(latents=self.taesdv.encode_frame(x.mul(0.5).add_(0.5)))
    def decode(self, x, return_dict=None):
        print("decoding frame with taesdv")
        frame, self.mem = self.taesdv.decode_frame(x, mem=self.mem)
        return (frame.mul(2).sub_(1),)

stream.vae = DiffusersStyleStatefulTAESDVWrapper().to("cuda")
```

(This assumes that the `decode` calls will happen in per-frame order, which I think is the case for most StreamDiffusion workflows? But if not, you'd need to manage the `mem` more carefully)

**Comment by ccarmatic** [comment]
Thank you and happy holidays, this seems to work, I am using Streamdiffusion with my webcam , so it is indeed working with one frame at a time
Now the output video stream is marginally less flickery when there is movement in the webcam , compared to using TAESD... 
But the consistency is still very poor for moving objects on camera
Is it possible to do a sort of 'motion blur' for the latent image to maintain as much consistency as possible?

**Comment by madebyollin** [comment]
@ccarmatic I think https://github.com/Jeff-LiangF/streamv2v may reduce flickering (at least for mostly-static scenes), and there are some other works like https://live2diff.github.io which also claim improvement.

I have been waiting for someone to just finetune a proper causal video diffusion model (like a "previous-frames controlnet" for SD or something) which should be the real solution, but AFAICT no one has done so yet :/

**Comment by ccarmatic** [comment]
The ultimate solution would be a model trained on actual videos , which not only takes the video frames as training data, but also the motion vectors as well
So during the inference, it will take 2 inputs... The current frame from the video feed, as well as the motion vectors calculated between the current and previous frames ....The motion vectors can be generated by i.e. one of OpenCV's optical flow solutions 

Modern Nvidia GPU's have dedicated hardware for calculating motion vectors , accessible by i.e. `cv2.cuda.NvidiaOpticalFlow_2_0` which is what I use in my Python script and it can calculate a dense optical field basically instantly compared to how long it takes the diffuser to finish one frame

But failing that, my other idea was that, based on my understanding, currently the diffuser is making a whole new frame every time from scratch... What if it can re-use some data from the previous frame, this would save some processing as well as maintain consistency across frames

**Comment by ccarmatic** [comment]
But more relevant to TAESDV, is there a way we can increase the 'weight' or the 'influence' of the `mem` object? Such that the previous frame will have a bigger influence on the next frame

Also in my Python script, in my attempt to reduce the flickering of the output video feed, I am blending the output frame back into the input frame at a controllable ratio using `cv2.addWeighted ` ... What I found was that this created a feedback loop where alternate frames are diverging from one another , causing even greater flickering across the whole frame... So the solution was to blend across 2 previous frames, basically creating a rudimentary 'motion blur' input which creates a flicker-free output from the diffuser

Perhaps the same can hold true for for the `mem` object? Perhaps 2 different `mem` objects, to hold 2 previous frames' worth of 'residual' data, and because they are not direct image data, you can do more than simply calculate their weighted average - they can be applied at different points in the denoising process, which should lead to some interesting results...

**Comment by ccarmatic** [comment]
>     def encode(self, x):
>         return DotDict(latents=self.taesdv.encode_frame(x.mul(0.5).add_(0.5)))

Can I ask a question, what does this 'x' do? It has something to do with image tensors? 
Changing the numbers from 0.5 seems to have no noticable effect...

**Comment by madebyollin** [comment]
@ccarmatic 

> is there a way we can increase the 'weight' or the 'influence' of the mem object? Such that the previous frame will have a bigger influence on the next frame

Not that I know of; I think all of the flickering comes from the latent itself, not TAESDV memory.

> what does this 'x' do? It has something to do with image tensors?

For `encode`, `x` is the original video frame, and `encode` encodes that video frame into a latent/compressed frame (i.e. the opposite of `decode`). I think `encode` would only be run if your StreamDiffusion workflow consumes images and then encodes them to latents (but there might be some other encoding code used for this; you could add prints to be sure).
